= IIBA DMN Patterns
Matteo Mortari
2021-05-20
:jbake-type: talk
:jbake-tags: DMN, talk
:jbake-youtubeid: 0hQEMMRVHjA
:jbake-preview: talks/2021/iiba-dmn-patterns.png

## How to Capture Business Decisions using DMN: Introduction to Some Basic Patterns and Their Value

Businesses continuously make Business Decisions. Some of these decisions are strategic business decisions, but a lot are operational business decisions taken every day within every transaction. With the ever-increasing number of laws and regulations that may apply or regulate these operational business decisions, business analysts are more often called upon to document/specify how these business decisions are to be taken in order to provide transparency and to offer auditable traces of the actual decisions taken.

In this insightful session, we will introduce how business analysts can use DMN to capture the requirements for operational business decisions, some of the recurring basic patterns in modeling these business decisions and will even show how to transform these decision models into actual executable business decision services.
